spring.application.name=incident_ticket_api
server.port=8080
# temporarily exclude datasource auto-configuration to avoid errors related to missing datasource configuration
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration