spring.application.name=incident_ticket_api
server.port=8080

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/incident_ticket_db 
spring.datasource.username=incident_user
spring.datasource.password=incident_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha